# render.yaml

services:
  - type: web
    name: api-moto
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn moto_api.wsgi
    autoDeploy: true
    plan: free